version: '3'

services:

  portainer:
    image: cr.Portainer.io/portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - 8001:8001/tcp
      - 9443:9443/tcp
    networks:
      network:
        ipv4_address: 172.18.0.2


networks:
  network:
    ipam:
      config:
        - subnet: "172.18.0.0/16"
          gateway: 172.18.0.1

volumes:
  portainer_data:
    driver: local